apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-frontend
  namespace: gio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hr-frontend
  template:
    metadata:
      labels:
        app: hr-frontend
    spec:
      containers:
      - name: frontend
        image: giobibleacr2032.azurecr.io/hr-frontend:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: shared-data
          mountPath: /data
      volumes:
      - name: shared-data
        emptyDir: {}